export interface TerminalTheme {
  id: string;
  name: string;
  mode: "dark" | "light";
  /** Swatch color shown in the picker */
  swatch: string;
  background: string;
  foreground: string;
  cursor: string;
  cursorAccent: string;
  selectionBackground: string;
  black: string;
  red: string;
  green: string;
  yellow: string;
  blue: string;
  magenta: string;
  cyan: string;
  white: string;
  brightBlack: string;
  brightRed: string;
  brightGreen: string;
  brightYellow: string;
  brightBlue: string;
  brightMagenta: string;
  brightCyan: string;
  brightWhite: string;
}

export const themes: TerminalTheme[] = [
  {
    id: "emerald",
    name: "Emerald",
    mode: "dark",
    swatch: "#34d399",
    background: "#09090b",
    foreground: "#d4d4d8",
    cursor: "#34d399",
    cursorAccent: "#09090b",
    selectionBackground: "#34d39930",
    black: "#18181b",
    red: "#f87171",
    green: "#34d399",
    yellow: "#fbbf24",
    blue: "#60a5fa",
    magenta: "#c084fc",
    cyan: "#22d3ee",
    white: "#e4e4e7",
    brightBlack: "#3f3f46",
    brightRed: "#fca5a5",
    brightGreen: "#6ee7b7",
    brightYellow: "#fde68a",
    brightBlue: "#93c5fd",
    brightMagenta: "#d8b4fe",
    brightCyan: "#67e8f9",
    brightWhite: "#ffffff",
  },
  {
    id: "dracula",
    name: "Dracula",
    mode: "dark",
    swatch: "#bd93f9",
    background: "#282a36",
    foreground: "#f8f8f2",
    cursor: "#f8f8f2",
    cursorAccent: "#282a36",
    selectionBackground: "#44475a",
    black: "#21222c",
    red: "#ff5555",
    green: "#50fa7b",
    yellow: "#f1fa8c",
    blue: "#6272a4",
    magenta: "#bd93f9",
    cyan: "#8be9fd",
    white: "#f8f8f2",
    brightBlack: "#6272a4",
    brightRed: "#ff6e6e",
    brightGreen: "#69ff94",
    brightYellow: "#ffffa5",
    brightBlue: "#d6acff",
    brightMagenta: "#ff92df",
    brightCyan: "#a4ffff",
    brightWhite: "#ffffff",
  },
  {
    id: "nord",
    name: "Nord",
    mode: "dark",
    swatch: "#88c0d0",
    background: "#2e3440",
    foreground: "#d8dee9",
    cursor: "#d8dee9",
    cursorAccent: "#2e3440",
    selectionBackground: "#434c5e",
    black: "#3b4252",
    red: "#bf616a",
    green: "#a3be8c",
    yellow: "#ebcb8b",
    blue: "#81a1c1",
    magenta: "#b48ead",
    cyan: "#88c0d0",
    white: "#e5e9f0",
    brightBlack: "#4c566a",
    brightRed: "#bf616a",
    brightGreen: "#a3be8c",
    brightYellow: "#ebcb8b",
    brightBlue: "#81a1c1",
    brightMagenta: "#b48ead",
    brightCyan: "#8fbcbb",
    brightWhite: "#eceff4",
  },
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    mode: "dark",
    swatch: "#7aa2f7",
    background: "#1a1b26",
    foreground: "#c0caf5",
    cursor: "#c0caf5",
    cursorAccent: "#1a1b26",
    selectionBackground: "#33467c",
    black: "#15161e",
    red: "#f7768e",
    green: "#9ece6a",
    yellow: "#e0af68",
    blue: "#7aa2f7",
    magenta: "#bb9af7",
    cyan: "#7dcfff",
    white: "#a9b1d6",
    brightBlack: "#414868",
    brightRed: "#f7768e",
    brightGreen: "#9ece6a",
    brightYellow: "#e0af68",
    brightBlue: "#7aa2f7",
    brightMagenta: "#bb9af7",
    brightCyan: "#7dcfff",
    brightWhite: "#c0caf5",
  },
  {
    id: "solarized",
    name: "Solarized Dark",
    mode: "dark",
    swatch: "#268bd2",
    background: "#002b36",
    foreground: "#839496",
    cursor: "#839496",
    cursorAccent: "#002b36",
    selectionBackground: "#073642",
    black: "#073642",
    red: "#dc322f",
    green: "#859900",
    yellow: "#b58900",
    blue: "#268bd2",
    magenta: "#d33682",
    cyan: "#2aa198",
    white: "#eee8d5",
    brightBlack: "#586e75",
    brightRed: "#cb4b16",
    brightGreen: "#586e75",
    brightYellow: "#657b83",
    brightBlue: "#839496",
    brightMagenta: "#6c71c4",
    brightCyan: "#93a1a1",
    brightWhite: "#fdf6e3",
  },
  {
    id: "monokai",
    name: "Monokai",
    mode: "dark",
    swatch: "#a6e22e",
    background: "#272822",
    foreground: "#f8f8f2",
    cursor: "#f8f8f0",
    cursorAccent: "#272822",
    selectionBackground: "#49483e",
    black: "#272822",
    red: "#f92672",
    green: "#a6e22e",
    yellow: "#f4bf75",
    blue: "#66d9ef",
    magenta: "#ae81ff",
    cyan: "#a1efe4",
    white: "#f8f8f2",
    brightBlack: "#75715e",
    brightRed: "#f92672",
    brightGreen: "#a6e22e",
    brightYellow: "#f4bf75",
    brightBlue: "#66d9ef",
    brightMagenta: "#ae81ff",
    brightCyan: "#a1efe4",
    brightWhite: "#f9f8f5",
  },
  {
    id: "catppuccin",
    name: "Catppuccin",
    mode: "dark",
    swatch: "#cba6f7",
    background: "#1e1e2e",
    foreground: "#cdd6f4",
    cursor: "#f5e0dc",
    cursorAccent: "#1e1e2e",
    selectionBackground: "#45475a",
    black: "#45475a",
    red: "#f38ba8",
    green: "#a6e3a1",
    yellow: "#f9e2af",
    blue: "#89b4fa",
    magenta: "#cba6f7",
    cyan: "#94e2d5",
    white: "#bac2de",
    brightBlack: "#585b70",
    brightRed: "#f38ba8",
    brightGreen: "#a6e3a1",
    brightYellow: "#f9e2af",
    brightBlue: "#89b4fa",
    brightMagenta: "#cba6f7",
    brightCyan: "#94e2d5",
    brightWhite: "#a6adc8",
  },
  {
    id: "rose-pine",
    name: "Rose Pine",
    mode: "dark",
    swatch: "#c4a7e7",
    background: "#191724",
    foreground: "#e0def4",
    cursor: "#524f67",
    cursorAccent: "#e0def4",
    selectionBackground: "#2a283e",
    black: "#26233a",
    red: "#eb6f92",
    green: "#31748f",
    yellow: "#f6c177",
    blue: "#9ccfd8",
    magenta: "#c4a7e7",
    cyan: "#ebbcba",
    white: "#e0def4",
    brightBlack: "#6e6a86",
    brightRed: "#eb6f92",
    brightGreen: "#31748f",
    brightYellow: "#f6c177",
    brightBlue: "#9ccfd8",
    brightMagenta: "#c4a7e7",
    brightCyan: "#ebbcba",
    brightWhite: "#e0def4",
  },
  {
    id: "everforest",
    name: "Everforest Dark",
    mode: "dark",
    swatch: "#a7c080",
    background: "#2d353b",
    foreground: "#d3c6aa",
    cursor: "#d3c6aa",
    cursorAccent: "#2d353b",
    selectionBackground: "#475258",
    black: "#343f44",
    red: "#e67e80",
    green: "#a7c080",
    yellow: "#dbbc7f",
    blue: "#7fbbb3",
    magenta: "#d699b6",
    cyan: "#83c092",
    white: "#d3c6aa",
    brightBlack: "#5c6a72",
    brightRed: "#e67e80",
    brightGreen: "#a7c080",
    brightYellow: "#dbbc7f",
    brightBlue: "#7fbbb3",
    brightMagenta: "#d699b6",
    brightCyan: "#83c092",
    brightWhite: "#e4e1cd",
  },
  {
    id: "gruvbox",
    name: "Gruvbox Dark",
    mode: "dark",
    swatch: "#fabd2f",
    background: "#282828",
    foreground: "#ebdbb2",
    cursor: "#ebdbb2",
    cursorAccent: "#282828",
    selectionBackground: "#3c3836",
    black: "#282828",
    red: "#cc241d",
    green: "#98971a",
    yellow: "#d79921",
    blue: "#458588",
    magenta: "#b16286",
    cyan: "#689d6a",
    white: "#a89984",
    brightBlack: "#928374",
    brightRed: "#fb4934",
    brightGreen: "#b8bb26",
    brightYellow: "#fabd2f",
    brightBlue: "#83a598",
    brightMagenta: "#d3869b",
    brightCyan: "#8ec07c",
    brightWhite: "#ebdbb2",
  },
  // ---- Light themes ----
  {
    id: "github-light",
    name: "GitHub Light",
    mode: "light",
    swatch: "#0969da",
    background: "#ffffff",
    foreground: "#1f2328",
    cursor: "#044289",
    cursorAccent: "#ffffff",
    selectionBackground: "#0969da20",
    black: "#24292f",
    red: "#cf222e",
    green: "#116329",
    yellow: "#4d2d00",
    blue: "#0969da",
    magenta: "#8250df",
    cyan: "#1b7c83",
    white: "#6e7781",
    brightBlack: "#57606a",
    brightRed: "#a40e26",
    brightGreen: "#1a7f37",
    brightYellow: "#633c01",
    brightBlue: "#218bff",
    brightMagenta: "#a475f9",
    brightCyan: "#3192aa",
    brightWhite: "#8c959f",
  },
  {
    id: "solarized-light",
    name: "Solarized Light",
    mode: "light",
    swatch: "#268bd2",
    background: "#fdf6e3",
    foreground: "#657b83",
    cursor: "#586e75",
    cursorAccent: "#fdf6e3",
    selectionBackground: "#eee8d5",
    black: "#073642",
    red: "#dc322f",
    green: "#859900",
    yellow: "#b58900",
    blue: "#268bd2",
    magenta: "#d33682",
    cyan: "#2aa198",
    white: "#eee8d5",
    brightBlack: "#586e75",
    brightRed: "#cb4b16",
    brightGreen: "#586e75",
    brightYellow: "#657b83",
    brightBlue: "#839496",
    brightMagenta: "#6c71c4",
    brightCyan: "#93a1a1",
    brightWhite: "#fdf6e3",
  },
  {
    id: "catppuccin-latte",
    name: "Catppuccin Latte",
    mode: "light",
    swatch: "#8839ef",
    background: "#eff1f5",
    foreground: "#4c4f69",
    cursor: "#dc8a78",
    cursorAccent: "#eff1f5",
    selectionBackground: "#acb0be",
    black: "#5c5f77",
    red: "#d20f39",
    green: "#40a02b",
    yellow: "#df8e1d",
    blue: "#1e66f5",
    magenta: "#8839ef",
    cyan: "#179299",
    white: "#acb0be",
    brightBlack: "#6c6f85",
    brightRed: "#d20f39",
    brightGreen: "#40a02b",
    brightYellow: "#df8e1d",
    brightBlue: "#1e66f5",
    brightMagenta: "#8839ef",
    brightCyan: "#179299",
    brightWhite: "#bcc0cc",
  },
  {
    id: "rose-pine-dawn",
    name: "Rose Pine Dawn",
    mode: "light",
    swatch: "#907aa9",
    background: "#faf4ed",
    foreground: "#575279",
    cursor: "#575279",
    cursorAccent: "#faf4ed",
    selectionBackground: "#dfdad9",
    black: "#575279",
    red: "#b4637a",
    green: "#286983",
    yellow: "#ea9d34",
    blue: "#56949f",
    magenta: "#907aa9",
    cyan: "#d7827e",
    white: "#f2e9e1",
    brightBlack: "#9893a5",
    brightRed: "#b4637a",
    brightGreen: "#286983",
    brightYellow: "#ea9d34",
    brightBlue: "#56949f",
    brightMagenta: "#907aa9",
    brightCyan: "#d7827e",
    brightWhite: "#faf4ed",
  },
  {
    id: "everforest-light",
    name: "Everforest Light",
    mode: "light",
    swatch: "#8da101",
    background: "#fdf6e3",
    foreground: "#5c6a72",
    cursor: "#5c6a72",
    cursorAccent: "#fdf6e3",
    selectionBackground: "#e6e2cc",
    black: "#5c6a72",
    red: "#f85552",
    green: "#8da101",
    yellow: "#dfa000",
    blue: "#3a94c5",
    magenta: "#df69ba",
    cyan: "#35a77c",
    white: "#e6e2cc",
    brightBlack: "#939f91",
    brightRed: "#f85552",
    brightGreen: "#8da101",
    brightYellow: "#dfa000",
    brightBlue: "#3a94c5",
    brightMagenta: "#df69ba",
    brightCyan: "#35a77c",
    brightWhite: "#fdf6e3",
  },
  {
    id: "gruvbox-light",
    name: "Gruvbox Light",
    mode: "light",
    swatch: "#d65d0e",
    background: "#fbf1c7",
    foreground: "#3c3836",
    cursor: "#3c3836",
    cursorAccent: "#fbf1c7",
    selectionBackground: "#ebdbb2",
    black: "#3c3836",
    red: "#cc241d",
    green: "#98971a",
    yellow: "#d79921",
    blue: "#458588",
    magenta: "#b16286",
    cyan: "#689d6a",
    white: "#ebdbb2",
    brightBlack: "#928374",
    brightRed: "#9d0006",
    brightGreen: "#79740e",
    brightYellow: "#b57614",
    brightBlue: "#076678",
    brightMagenta: "#8f3f71",
    brightCyan: "#427b58",
    brightWhite: "#fbf1c7",
  },
];

export interface TerminalFont {
  id: string;
  name: string;
  fontFamily: string;
  /** Google Fonts URL to load, if not a system font */
  googleFontsUrl?: string;
}

export const fonts: TerminalFont[] = [
  {
    id: "ibm-plex-mono",
    name: "IBM Plex Mono",
    fontFamily: "'IBM Plex Mono', monospace",
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600&display=swap",
  },
  {
    id: "jetbrains-mono",
    name: "JetBrains Mono",
    fontFamily: "'JetBrains Mono', monospace",
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600&display=swap",
  },
  {
    id: "fira-code",
    name: "Fira Code",
    fontFamily: "'Fira Code', monospace",
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Fira+Code:wght@400;500;600&display=swap",
  },
  {
    id: "source-code-pro",
    name: "Source Code Pro",
    fontFamily: "'Source Code Pro', monospace",
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500;600&display=swap",
  },
  {
    id: "inconsolata",
    name: "Inconsolata",
    fontFamily: "'Inconsolata', monospace",
    googleFontsUrl: "https://fonts.googleapis.com/css2?family=Inconsolata:wght@400;500;600&display=swap",
  },
  {
    id: "sf-mono",
    name: "SF Mono",
    fontFamily: "'SF Mono', monospace",
  },
  {
    id: "menlo",
    name: "Menlo",
    fontFamily: "Menlo, monospace",
  },
  {
    id: "monaco",
    name: "Monaco",
    fontFamily: "Monaco, monospace",
  },
];

export const DEFAULT_FONT_ID = "ibm-plex-mono";

export function getFontById(id: string): TerminalFont {
  return fonts.find((f) => f.id === id) ?? fonts[0];
}

/** Load a Google Font if needed. No-ops if already loaded or not a Google Font. */
export function ensureFontLoaded(font: TerminalFont): void {
  if (!font.googleFontsUrl || typeof document === "undefined") return;
  const linkId = `font-${font.id}`;
  if (document.getElementById(linkId)) return;
  const link = document.createElement("link");
  link.id = linkId;
  link.rel = "stylesheet";
  link.href = font.googleFontsUrl;
  document.head.appendChild(link);
}

export const DEFAULT_DARK_THEME = "gruvbox";
export const DEFAULT_LIGHT_THEME = "github-light";

export function getThemeById(id: string): TerminalTheme {
  return themes.find((t) => t.id === id) ?? themes[0];
}

export function getDefaultThemeForMode(mode: "dark" | "light"): TerminalTheme {
  return getThemeById(mode === "dark" ? DEFAULT_DARK_THEME : DEFAULT_LIGHT_THEME);
}

export function themesForMode(mode: "dark" | "light"): TerminalTheme[] {
  return themes.filter((t) => t.mode === mode);
}

/** Extract the xterm ITheme object from our theme definition */
export function toXtermTheme(theme: TerminalTheme) {
  const { id, name, mode, swatch, ...xtermFields } = theme;
  return xtermFields;
}
